---
parser: babel-eslint
rules:
  react/prop-types: off
env:
  es6: true
  browser: true
  node: true
parserOptions:
  ecmaVersion: 2020
  sourceType: module
  ecmaFeatures:
    jsx: true
plugins:
  - react
settings:
  react:
    version: detect
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:prettier/recommended
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
