---
rules:
  no-undef: error
  no-unused-vars: error
env:
  es6: true
  node: true
parserOptions:
  ecmaVersion: 2020
  sourceType: module
extends:
  - eslint:recommended
  - plugin:prettier/recommended
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
