---
rules:
  no-undef: error
  no-unused-vars: error
  react/prop-types: off
env:
  es6: true
  browser: true
  node: true
parserOptions:
  ecmaVersion: 2020
  sourceType: module
  ecmaFeatures:
    jsx: true
plugins:
  - react
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:prettier/recommended
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
