images:
  full: [1200, 1200, { fit: 'inside' }]
  thumb: [200, null]
title: Mojo (July 14, 2009 - May 23, 2020)
description: >
  Mojo was the friendliest cat. He loved new people and would come and
  sit right on anyone's lap. Much like a dog he would follow me from
  room to room and always demanded attention. If I didn't give him enough
  attention he would let me know my biting me.
sections:
  top:
    title: Has to be Right on Top and in My Face
    content: >
      Whenever I finished worked and hopped on the couch, this little guy would
      always have to be right on top of me all up in my face.
  buddha:
    title: The Buddha
    content: >
      A common characteristic of Scottish Folds is to sit like a Buddha.
      And Mojo was no exception. He loved to sit on his little cat butt!
  people:
    title: Loves People
  costume:
    title: In Costume
  desk:
    title: On the Desk
  box:
    title: Mojo loves boxes
  fire:
    title: NBPD Rescue from a Burning Building
  pets:
    title: Siblings
  snuggle:
    title: Loves to Snuggle
  '.':
    title: More Photos
