title: Mojo (July 14, 2009 - May 23, 2020)
description: >
  Mojo was the friendliest cat. He loved new people and would come and
  sit right on anyone's lap. Much like a dog he would follow me from
  room to room and always demanded attention. If I didn't give him enough
  attention he would let me know my biting me.
sections:
  buddha:
    title: The Buddha
    content: >
      A common characteristic of Scottish Folds is to sit like a Buddha.
  people:
    title: Loves People
  costume:
    title: In Costume
  desk:
    title: On the Desk
  box:
    title: Mojo loves boxes
  fire:
    title: NBPD Rescue from a Burning Building
  pets:
    title: Siblings
  snuggle:
    title: Loves to Snuggle
  top:
    title: Has to be Right on Top and in My Face
  ".":
    title: More Photos
