title: Mojo
description: >
  Lorem Ipsum is simply dummy text of the printing and typesetting
  industry. Lorem Ipsum has been the industry's standard dummy text
  ever since the 1500s, when an unknown printer took a galley of type
  and scrambled it to make a type specimen book. It has survived not
  only five
sections:
  buddha:
    title: The Buddha
    content: >
      A common characteristic of Scottish Folds is to sit like a Buddha.
  people:
    title: Loves People
  costume:
    title: In Costume
  desk:
    title: On the Desk
  box:
    title: Mojo loves boxes
  fire:
    title: NBPD Rescue from a Burning Building
  pets:
    title: Siblings
  snuggle:
    title: Loves to Snuggle
  top:
    title: Has to be Right on Top and in My Face
  ".":
    title: More Photos
